image: python:3.8
test:
    stage: test
    before_script:
        - pip install -r requirements.txt
        - apt install npm
        - npm install -g jest
    script:
        - python manage.py migrate
        - python manage.py test
        - npm run test

staging:
    stage: deploy
    before_script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - npm install
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY --run='python manage.py migrate'
        - python manage.py compress